---
ID: "6c9392f9-7c16-44e9-b198-6ebe5a47067d"
Parent: "08d9417d-5071-46ff-896b-eb76b0790526"
Template: "3784a738-6d25-4283-98e2-759db694efd7"
Path: /sitecore/content/Verticals/Financial/Settings
BranchID: "45cf9f42-b3ac-4412-aab9-f8441c7e448e"
SharedFields:
- ID: "0129da3f-8c86-4591-ae32-6ec923413923"
  Hint: DictionaryDomain
  Value: "{58307E4B-EC38-4EB0-AE47-6C238E33B7CD}"
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{C2DC4690-AF44-48C7-BB21-90D1AD246732}"
- ID: "300fb7a0-b27f-44dd-9af0-b37a19723e0e"
  Hint: RouteTemplateName
  Value: Settings Route
- ID: "32ce6bbe-4217-46e5-9335-42793884cbe3"
  Hint: AppTemplate
  Value: "{598C1F44-5FD6-4E7B-B77F-D09D2E4090EE}"
- ID: "3e4f559f-8e59-4405-b50d-619811371f6c"
  Hint: Name
  Value: Financial
- ID: "5764d2d4-724d-4313-a81b-9246c911faff"
  Hint: AppDatasourcesPath
  Value: "{5C48BD53-E997-45FC-B318-672CFA349BB3}"
- ID: "5ca117eb-8782-4a4f-9f2f-30de31fc2e34"
  Hint: PlaceholdersPath
  Value: "{886787BC-AFE2-43A0-BC26-38178F98AD34}"
- ID: "72e83c8d-3578-4e50-b4c0-93a78a1729f2"
  Hint: FilesystemPath
  Value: /dist/Financial
- ID: "9016141c-ff51-40f2-9135-40f5161b9784"
  Hint: ServerSideRenderingEngine
  Value: http
- ID: "a7bbad73-b933-49ff-95c8-1c269cb35e7c"
  Hint: DictionaryPath
  Value: "{58307E4B-EC38-4EB0-AE47-6C238E33B7CD}"
- ID: "af332c24-fe17-41e7-8caf-8e64c588fe72"
  Hint: EditingTheme
  Value: "{3BCAB9EF-1E4F-4C23-B452-783BB82AA686}"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 2000
- ID: "c8d002f9-9518-4c5e-9baa-6617e13f0797"
  Hint: LayoutPath
  Value: "{96E5F4BA-A2CF-4A4C-A4E7-64DA88226362}"
- ID: "e8881464-38af-4655-be4a-ee10586578a2"
  Hint: Templates
  Value: "{8B77B250-9318-47A8-9B33-6D35B27F5897}"
- ID: "f29428d5-1285-48b8-a884-44057965829a"
  Hint: RenderingsPath
  Value: "{6630C97B-F037-4F1F-87BC-907C43F167D1}"
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{0FEEB907-58F0-44DE-B08C-2F43C063D0A5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c74297be-5e61-40c9-96df-6044a8a2f90b"
