---
ID: "3570a064-ead2-4089-99b5-c741c24fd42b"
Parent: "5dce5575-a107-421a-aefc-d67ea7b846fa"
Template: "5dce5575-a107-421a-aefc-d67ea7b846fa"
Path: /sitecore/templates/Project/Verticals/Partial Designs/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {139C4CAC-D954-45CF-BB38-6000CEFA64D4}
    {FD2059FD-6043-4DFE-8C04-E2437CE87634}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240227T210744Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\alexander.doroshenko@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\alexander.doroshenko@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "86ac83cf-d1a0-46bc-9d2a-65ee108fe2e8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\alexander.doroshenko@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240227T210745Z
